package org.example.project

enum class AppLanguage { ENGLISH, ROMANIAN }

data class AppStrings(
    // ── Bottom nav (shared across all screens)
    val navHistory: String,
    val navScan: String,
    val navFiles: String,

    // ── HomeScreen / Scanner
    val scannerTitle: String,
    val heroText: String,
    val heroSubtitle: String,
    val uploadTitle: String,
    val uploadSubtitleMobile: String,
    val uploadSubtitleDesktop: String,
    val browseBtn: String,
    val quickScan: String,
    val dropToScan: String,

    // ── Identity card dialog (shared between HomeScreen and FilesScreen)
    val idVerifiedTitle: String,
    val idVerifiedSubtitle: String,
    val gotIt: String,

    // ── HistoryScreen
    val historyTitle: String,
    val historyHero1: String,
    val historyHero2: String,
    val historySubtitle: String,
    val filterAll: String,
    val filterActive: String,
    val filterRevoked: String,
    val revokeBtn: String,
    val confirmYes: String,
    val confirmNo: String,
    val revokedBadge: String,

    // ── FilesScreen
    val filesTitle: String,
    val filesHero1: String,
    val filesHero2: String,
    val statApproved: String,
    val statEncrypted: String,
    val filesFilterAll: String,
    val filesFilterUploaded: String,
    val filesFilterWaiting: String,
    val filesFilterApproved: String,
    val statusUploaded: String,
    val statusWaiting: String,
    val statusApproved: String,
    val emptyTitle: String,
    val emptySubtitle: String,
    val buletinTitle: String,
    val buletinSubtitle: String,
    val buletinVerified: String,
    val generateKeyBtn: String,
    val copyKeyBtn: String,
    val copiedLabel: String,
    val closeBtn: String,

    // ── ProfileScreen
    val profileTitle: String,
    val profileSecurity: String,
    val profileSecurityValue: String,
    val profileMemberSince: String,
    val profileMemberSinceValue: String,
    val profileSession: String,
    val profileSessionValue: String,
    val profileLanguageLabel: String,
    val profileLogout: String
)

fun buildStrings(lang: AppLanguage): AppStrings = when (lang) {
    AppLanguage.ENGLISH -> AppStrings(
        navHistory               = "HISTORY",
        navScan                  = "SCAN",
        navFiles                 = "FILES",
        scannerTitle             = "Scanner",
        heroText                 = "skip unnecessary\nsharing with us",
        heroSubtitle             = "end to end encryption",
        uploadTitle              = "UPLOAD A FILE",
        uploadSubtitleMobile     = "Drag and drop or browse gallery",
        uploadSubtitleDesktop    = "Drag & drop here, or click anywhere to browse",
        browseBtn                = "Browse",
        quickScan                = "QUICK SCAN",
        dropToScan               = "Drop file to scan",
        idVerifiedTitle          = "Identity card added and verified",
        idVerifiedSubtitle       = "You can verify your age or your citizenship on other apps",
        gotIt                    = "Got it",
        historyTitle             = "History",
        historyHero1             = "who used",
        historyHero2             = "your keys",
        historySubtitle          = "complete audit trail · end-to-end encrypted",
        filterAll                = "All",
        filterActive             = "Active",
        filterRevoked            = "Revoked",
        revokeBtn                = "Revoke",
        confirmYes               = "Yes",
        confirmNo                = "No",
        revokedBadge             = "Revoked",
        filesTitle               = "Files",
        filesHero1               = "your documents",
        filesHero2               = "secured",
        statApproved             = "Approved",
        statEncrypted            = "Encrypted",
        filesFilterAll           = "All",
        filesFilterUploaded      = "Uploaded",
        filesFilterWaiting       = "Pending",
        filesFilterApproved      = "Approved",
        statusUploaded           = "Uploaded",
        statusWaiting            = "Pending",
        statusApproved           = "Approved",
        emptyTitle               = "No documents found",
        emptySubtitle            = "Try a different filter or upload a file",
        buletinTitle             = "Identity Card",
        buletinSubtitle          = "Verified identity card",
        buletinVerified          = "Verified",
        generateKeyBtn           = "Generate key",
        copyKeyBtn               = "Copy key",
        copiedLabel              = "Copied!",
        closeBtn                 = "Close",
        profileTitle             = "Profile",
        profileSecurity          = "Security",
        profileSecurityValue     = "End-to-end encrypted",
        profileMemberSince       = "Member since",
        profileMemberSinceValue  = "April 2026",
        profileSession           = "Documents scanned",
        profileSessionValue      = "Active session",
        profileLanguageLabel     = "Language",
        profileLogout            = "Log out"
    )
    AppLanguage.ROMANIAN -> AppStrings(
        navHistory               = "ISTORIC",
        navScan                  = "SCANARE",
        navFiles                 = "FIȘIERE",
        scannerTitle             = "Scaner",
        heroText                 = "sari peste partajarea\ninutilă cu noi",
        heroSubtitle             = "criptare end to end",
        uploadTitle              = "ÎNCARCĂ UN FIȘIER",
        uploadSubtitleMobile     = "Trage și plasează sau răsfoiește",
        uploadSubtitleDesktop    = "Trage & plasează sau click pentru a răsfoi",
        browseBtn                = "Răsfoiește",
        quickScan                = "SCANARE RAPIDĂ",
        dropToScan               = "Plasează pentru scanare",
        idVerifiedTitle          = "Carte de identitate adăugată și verificată",
        idVerifiedSubtitle       = "Îți poți verifica vârsta sau cetățenia în alte aplicații",
        gotIt                    = "Am înțeles",
        historyTitle             = "Istoric",
        historyHero1             = "cine a folosit",
        historyHero2             = "cheile tale",
        historySubtitle          = "jurnal de acces complet · criptat end-to-end",
        filterAll                = "Toate",
        filterActive             = "Active",
        filterRevoked            = "Revocat",
        revokeBtn                = "Revocă",
        confirmYes               = "Da",
        confirmNo                = "Nu",
        revokedBadge             = "Revocat",
        filesTitle               = "Fișiere",
        filesHero1               = "documentele",
        filesHero2               = "tale sigure",
        statApproved             = "Aprobate",
        statEncrypted            = "Criptate",
        filesFilterAll           = "Toate",
        filesFilterUploaded      = "Încărcate",
        filesFilterWaiting       = "În așteptare",
        filesFilterApproved      = "Aprobate",
        statusUploaded           = "Încărcat",
        statusWaiting            = "În așteptare",
        statusApproved           = "Aprobat",
        emptyTitle               = "Niciun document găsit",
        emptySubtitle            = "Încearcă alt filtru sau încarcă un fișier",
        buletinTitle             = "Buletin",
        buletinSubtitle          = "Carte de identitate verificată",
        buletinVerified          = "Verificat",
        generateKeyBtn           = "Generează cheie",
        copyKeyBtn               = "Copiază cheia",
        copiedLabel              = "Copiat!",
        closeBtn                 = "Închide",
        profileTitle             = "Profil",
        profileSecurity          = "Securitate",
        profileSecurityValue     = "Criptat end-to-end",
        profileMemberSince       = "Membru din",
        profileMemberSinceValue  = "Aprilie 2026",
        profileSession           = "Documente scanate",
        profileSessionValue      = "Sesiune activă",
        profileLanguageLabel     = "Limbă",
        profileLogout            = "Deconectare"
    )
}